CREATE TEMP TABLE descriptions_data_quality AS 
  SELECT dq.Articlenumber, 
  	 dq.Language,
         dq.DQ_Short_Desc,
  	 dq.DQ_Short_Desc_2, 
         dq.DQ_Long_Desc,
         SUM(dq.DQ_Short_Desc + dq.DQ_Short_Desc_2 + dq.DQ_Long_Desc) AS Total_descriptions
         FROM (SELECT
	       ps.Articlenumber,
               ps.Language,
               CASE WHEN ps.Short_description = '' OR ps.Short_description IS NULL THEN 0 ELSE 1 END AS 'DQ_Short_Desc',
               CASE WHEN ps.Short_description_2 = '' OR ps.Short_description_2 IS NULL THEN 0 ELSE 1 END AS 'DQ_Short_Desc_2',
               CASE WHEN ps.Long_description = '' OR ps.Long_description IS NULL THEN 0 ELSE 1 END AS 'DQ_Long_Desc'
							 FROM product_descriptions ps) dq
  	       GROUP BY dq.Articlenumber, 
  	                dq.Language,
  			dq.DQ_Short_Desc,
  			dq.DQ_Short_Desc_2, 
         		dq.DQ_Long_Desc;

CREATE TEMP TABLE properties_data_quality AS
SELECT dq.Manufacturernumber,
         dq.Articlenumber,
	 dq.DQ_EAN,
	 dq.DQ_Technical_details,
	 dq.DQ_Product_category,
         dq.DQ_Technical_specifications,
         dq.DQ_Picture_normal_reduced,
         dq.DQ_Depth_m,
         dq.DQ_Width_m,
         dq.DQ_Length_mv,
         dq.DQ_Weight_kg,
         dq.DQ_Delivery_time_days,
         dq.DQ_Type_of_product,
         dq.DQ_Price_quantity,
         dq.DQ_ETIM_Features,
         dq.DQ_ETIM,
         dq.DQ_ECLASS_Features,
         dq.DQ_ECLASS,
         dq.DQ_PROFICLASS_Features,
         dq.DQ_PROFICLASS,
         dq.DQ_Product_features,
         SUM(dq.DQ_EAN + dq.DQ_Technical_details + dq.DQ_Product_category + dq.DQ_Technical_specifications + dq.DQ_Picture_normal_reduced + dq.DQ_Depth_m + dq.DQ_Width_m + dq.DQ_Length_mv + dq.DQ_Weight_kg + dq.DQ_Delivery_time_days + dq.DQ_Type_of_product + dq.DQ_Price_quantity + dq.DQ_ETIM_Features + dq.DQ_ETIM + dq.DQ_ECLASS_Features + dq.DQ_ECLASS + dq.DQ_PROFICLASS_Features + dq.DQ_PROFICLASS + dq.DQ_Product_features) AS Total_properties
         FROM (SELECT
               ps.Manufacturernumber,
               ps.Articlenumber,
               CASE WHEN ps.EAN = '' OR ps.EAN IS NULL THEN 0 ELSE 1 END AS 'DQ_EAN',
               CASE WHEN ps.Technical_details = '' OR ps.Technical_details IS NULL THEN 0 ELSE 1 END AS 'DQ_Technical_details',
               CASE WHEN ps.Product_category = '' OR ps.Product_category IS NULL THEN 0 ELSE 1 END AS 'DQ_Product_category',
               CASE WHEN ps.Technical_specifications = '' OR ps.Technical_specifications IS NULL THEN 0 ELSE 1 END AS 'DQ_Technical_specifications',
               CASE WHEN ps.Picture_normal_reduced = '' OR ps.Picture_normal_reduced IS NULL THEN 0 ELSE 1 END AS 'DQ_Picture_normal_reduced',
               CASE WHEN ps.Depth_m = '' OR ps.Depth_m IS NULL THEN 0 ELSE 1 END AS 'DQ_Depth_m',
               CASE WHEN ps.Width_m = '' OR ps.Width_m IS NULL THEN 0 ELSE 1 END AS 'DQ_Width_m',
               CASE WHEN ps.Length_m = '' OR ps.Length_m IS NULL THEN 0 ELSE 1 END AS 'DQ_Length_mv',
               CASE WHEN ps.Weight_kg = '' OR ps.Weight_kg IS NULL THEN 0 ELSE 1 END AS 'DQ_Weight_kg',
               CASE WHEN ps.Delivery_time_days = '' OR ps.Delivery_time_days IS NULL THEN 0 ELSE 1 END AS 'DQ_Delivery_time_days',
               CASE WHEN ps.Type_of_product = '' OR ps.Type_of_product IS NULL THEN 0 ELSE 1 END AS 'DQ_Type_of_product',
               CASE WHEN ps.Price_quantity = '' OR ps.Price_quantity IS NULL THEN 0 ELSE 1 END AS 'DQ_Price_quantity',
               CASE WHEN ps.ETIM_Features = '' OR ps.ETIM_Features IS NULL THEN 0 ELSE 1 END AS 'DQ_ETIM_Features',
               CASE WHEN ps.ETIM = '' OR ps.ETIM IS NULL THEN 0 ELSE 1 END AS 'DQ_ETIM',
               CASE WHEN ps.ECLASS_Features = '' OR ps.ECLASS_Features IS NULL THEN 0 ELSE 1 END AS 'DQ_ECLASS_Features',
               CASE WHEN ps.ECLASS = '' OR ps.ECLASS IS NULL THEN 0 ELSE 1 END AS 'DQ_ECLASS',
               CASE WHEN ps.PROFICLASS_Features = '' OR ps.PROFICLASS_Features IS NULL THEN 0 ELSE 1 END AS 'DQ_PROFICLASS_Features',
               CASE WHEN ps.PROFICLASS = '' OR ps.PROFICLASS IS NULL THEN 0 ELSE 1 END AS 'DQ_PROFICLASS',
               CASE WHEN ps.Product_features = '' OR ps.Product_features IS NULL THEN 0 ELSE 1 END AS 'DQ_Product_features'
               FROM product_properties ps) dq
  	       GROUP BY dq.Manufacturernumber,
		        dq.Articlenumber,
		        dq.DQ_EAN,
		        dq.DQ_Technical_details,
		        dq.DQ_Product_category,
		        dq.DQ_Technical_specifications,
		        dq.DQ_Picture_normal_reduced,
		        dq.DQ_Depth_m,
		        dq.DQ_Width_m,
		        dq.DQ_Length_mv,
		        dq.DQ_Weight_kg,
		        dq.DQ_Delivery_time_days,
		        dq.DQ_Type_of_product,
		        dq.DQ_Price_quantity,
		        dq.DQ_ETIM_Features,
		        dq.DQ_ETIM,
		        dq.DQ_ECLASS_Features,
		        dq.DQ_ECLASS,
		        dq.DQ_PROFICLASS_Features,
		        dq.DQ_PROFICLASS,
		        dq.DQ_Product_features;
